# Generated by Django 6.0.2 on 2026-03-02 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the country, e.g., 'Ukraine'", max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the city, e.g., 'Lviv'", max_length=100)),
                ('country', models.ForeignKey(help_text='The country this city belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='stations.country')),
            ],
            options={
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the railway station', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of the station in decimal degrees', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of the station in decimal degrees', max_digits=9, null=True)),
                ('city', models.ForeignKey(help_text='The city where this station is located', on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='stations.city')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField(help_text='Distance between stations in kilometers.')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='stations.station')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='stations.station')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'destination'), name='unique_route')],
            },
        ),
    ]
