# Generated by Django 6.0 on 2026-05-25 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0002_alter_city_options_alter_country_options'),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(help_text='Departure date and time.')),
                ('arrival_time', models.DateTimeField(help_text='Arrival date and time.')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Current journey status.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crew', models.ManyToManyField(blank=True, help_text='Crew members assigned to the journey.', related_name='journeys', to='trains.crew')),
                ('route', models.ForeignKey(help_text='Route assigned to the journey.', on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='stations.route')),
                ('train', models.ForeignKey(help_text='Train assigned to the journey.', on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='trains.train')),
            ],
            options={
                'ordering': ['departure_time'],
                'indexes': [models.Index(fields=['departure_time'], name='journeys_jo_departu_407bfe_idx'), models.Index(fields=['status'], name='journeys_jo_status_9cccad_idx')],
            },
        ),
    ]
